services:
  - type: web
    name: lms-backend
    env: docker
    dockerfilePath: backend/Dockerfile.ubuntu
    plan: free
    branch: feature/sprint-2-user-story-2-security-settings
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080